import fancy_text
fancy_text.logo()
fancy_text.money_bag()
fancy_text.love_hart()
fancy_text.shotgun()
fancy_text.middle_finger()
fancy_text.mario()
fancy_text.scull()
fancy_text.guitar()
fancy_text.frog()
fancy_text.doom()
input()